'use strict';

// require('./shims');
require('./audiocontext');
const p5SOUND = require('./master');
require('./panner');
require('./soundfile');
require('./amplitude');
require('./fft');
require('./signal');
require('./oscillator');
require('./envelope');
require('./pulse');
require('./noise');
require('./audioin');
require('./filter');
require('./eq');
require('./panner3d');
require('./listener3d');
require('./delay');
require('./reverb');
require('./metro');
require('./looper');
require('./soundloop');
require('./compressor');
require('./soundRecorder');
// require('./peakdetect');
require('./gain');
require('./monosynth');
require('./polysynth');
require('./distortion');
require('./audioVoice');

module.exports = p5SOUND;
